# Generated by Django 4.1.1 on 2022-09-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volumes',
            options={'ordering': ['id'], 'verbose_name': 'Объем ведра', 'verbose_name_plural': 'Объемы ведер'},
        ),
        migrations.AlterField(
            model_name='products',
            name='brutto',
            field=models.DecimalField(decimal_places=1, default=999, max_digits=5, verbose_name='Грязный вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='netto',
            field=models.DecimalField(decimal_places=1, default=999, max_digits=5, verbose_name='Чистый вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buh.volumes', verbose_name='Объем'),
        ),
    ]
