# Generated by Django 4.1.1 on 2022-09-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0002_alter_volumes_options_alter_products_brutto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brutto',
        ),
        migrations.RemoveField(
            model_name='products',
            name='netto',
        ),
        migrations.RemoveField(
            model_name='products',
            name='volume',
        ),
    ]
