# Generated by Django 4.1.1 on 2022-09-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0003_remove_products_brutto_remove_products_netto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='volumes',
            options={},
        ),
        migrations.RemoveField(
            model_name='volumes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volumes',
            name='title',
        ),
        migrations.AddField(
            model_name='products',
            name='brutto',
            field=models.DecimalField(decimal_places=1, default=222, max_digits=5, verbose_name='Грязный вес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='netto',
            field=models.DecimalField(decimal_places=1, default=222, max_digits=5, verbose_name='Чистый вес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buh.volumes', verbose_name='Объем'),
        ),
    ]
