# Generated by Django 4.1.1 on 2022-09-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0004_naklad_pricelists_zakaz_alter_volumes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumes',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buh.volumes', verbose_name='Объем'),
        ),
    ]
