# Generated by Django 4.1.1 on 2022-09-29 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0005_volumes_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naklad',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование11111111')),
                ('netto', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Чистый вес')),
                ('brutto', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Грязный вес')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buh.volumes', verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='naklad',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.customers'),
            preserve_default=False,
        ),
    ]
