# Generated by Django 4.1.1 on 2022-09-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0006_alter_naklad_date_customers_naklad_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='naklad',
            name='zakaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.zakaz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naklad',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.addresses'),
            preserve_default=False,
        ),
    ]
