# Generated by Django 4.1.1 on 2022-09-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0008_alter_addresses_options_remove_volumes_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='brutto',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='netto',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='volume',
        ),
    ]
