# Generated by Django 4.1.1 on 2022-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0009_remove_customers_brutto_remove_customers_netto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumes',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
