# Generated by Django 4.1.1 on 2022-09-29 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0010_volumes_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volumes',
            options={'ordering': ['id'], 'verbose_name': 'Объем ведра', 'verbose_name_plural': 'Объемы ведер'},
        ),
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.addresses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя покупателя'),
        ),
        migrations.RemoveField(
            model_name='naklad',
            name='address',
        ),
        migrations.AlterField(
            model_name='naklad',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buh.customers', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='naklad',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='volumes',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='naklad',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.addresses', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
