# Generated by Django 4.1.1 on 2022-09-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0012_alter_naklad_options_remove_naklad_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.products', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
