# Generated by Django 4.1.1 on 2022-09-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0013_zakaz_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zakaz',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
