# Generated by Django 4.1.1 on 2022-09-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0014_zakaz_price_zakaz_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='volumes',
            name='name',
        ),
        migrations.AddField(
            model_name='pricelists',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.customers', verbose_name='Покупатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelists',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricelists',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='buh.products', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volumes',
            name='volume',
            field=models.CharField(default=1, max_length=50, verbose_name='Объем ведра'),
            preserve_default=False,
        ),
    ]
