# Generated by Django 4.1.1 on 2022-09-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0015_rename_name_addresses_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'ordering': ['id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
