# Generated by Django 4.1.1 on 2022-09-30 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0016_alter_zakaz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naklad',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 1), verbose_name='Дата'),
        ),
    ]
