# Generated by Django 4.1.1 on 2022-09-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0017_alter_naklad_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='customer_name',
        ),
    ]
