# Generated by Django 4.1.1 on 2022-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0018_rename_name_customers_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelists',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
