# Generated by Django 4.1.1 on 2022-10-01 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0019_pricelists_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naklad',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 2), verbose_name='Дата'),
        ),
    ]
