# Generated by Django 4.1.1 on 2022-10-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0020_alter_naklad_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Naklad',
            new_name='Naklads',
        ),
        migrations.DeleteModel(
            name='Zakaz',
        ),
    ]
