# Generated by Django 4.1.1 on 2022-10-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buh', '0021_rename_naklad_naklads_delete_zakaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('naklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buh.naklads', verbose_name='Накладная')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buh.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
